name: Cypress tests
on: 
  pull_request: {}
  push:
    branches:
      - main # or any other branches you wish to include
  schedule:
    - cron: 0 */6 * * * # This line runs the workflow every 6 hours

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install deps
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Start server
        run: yarn dev&

      - name: Run tests
        run: yarn test:cypress
        env:
          REPLAY_API_KEY: ${{ secrets.REPLAY_API_KEY }}