name: End-to-end tests
on: 
  pull_request: {}
  push:
    branches:
      - main # or any other branches you wish to include
  schedule:
    - cron: 0 */6 * * * # This line runs the workflow every 6 hours

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install deps and prepare
        uses: cypress-io/github-action@v5.1.0
        with:
          build: yarn build
          runTests: false

      - name: Run tests
        uses: cypress-io/github-action@v5.1.0
        with:
          start: yarn dev
          working-directory: ./packages/site
          install: false
          browser: replay-chromium
        env:
          REPLAY_API_KEY: ${{ secrets.REPLAY_API_KEY }}